pwd: /data/ephemeral/home/

name: STS

arch:
  type: STSModel
  args:
    plm_name: KLUE/roberta-small
    # snunlp/KR-ELECTRA-discriminator, BAAI/bge-multilingual-gemma2, kakaobank/kf-deberta-base, beomi/Llama-3-Open-Ko-8B
    dropout_rate: 0.1
    lora_r: 64
    lora_alpha: 32
    lora_dropout: 0.1

data_module:
  type: DataModule
  args:
    arch_type: ${arch.type}
    plm_name: ${arch.args.plm_name}
    dataset_name: STSDataset
    batch_size: 16
    shuffle: true
    train_path: ${pwd}/data/train.csv
    dev_path: ${pwd}/data/dev.csv
    test_path: ${pwd}/data/dev.csv
    predict_path: ${pwd}/data/test.csv
    max_length: 160
    col_info:
      label: label
      input: [sentence_1, sentence_2]

optimizer:
  type: AdamW
  args:
    lr: 0.00002
    weight_decay: 2e-5
    amsgrad: true

loss: l2_loss
metrics: [pearson]

lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1

trainer:
  epochs: 0
  save_dir: ${pwd}/saved/
  mode: max

wandb:
  enable: False
  project_name: backbone_model

saved_model_count: 5