pwd: /data/ephemeral/home/

name: STS

arch:
  type: WithDropout
  args:
    plm_name: snunlp/KR-ELECTRA-discriminator
    # snunlp/KR-ELECTRA-discriminator, BAAI/bge-multilingual-gemma2, kakaobank/kf-deberta-base
    dropout_rate: 0.0
    lora_r: 0.0
    lora_alpha: 0.0
    lora_dropout: 0.0

data_module:
  type: DataModule
  args:
    arch_type: ${arch.type}
    plm_name: ${arch.args.plm_name}
    dataset_name: STSDataset
    batch_size: 16
    shuffle: true
    train_path: ${pwd}/data/train.csv
    dev_path: ${pwd}/data/dev.csv
    test_path: ${pwd}/data/dev.csv
    predict_path: ${pwd}/data/test.csv
    max_length: 160
    col_info:
      label: label
      input: [sentence_1, sentence_2]

optimizer:
  type: AdamW
  args:
    lr: 0.00002
    weight_decay: 0
    amsgrad: true

loss: l2_loss
metrics: [pearson]

lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1

trainer:
  epochs: 15
  save_dir: ${pwd}/saved/
  mode: max

wandb:
  enable: False
  project_name: backbone_model

saved_model_count: 5